### ISSUE TITLE
Crash while navigating though nested JSON

### ISSUE THREAD

**Issue by docterd** [bitly/go-simplejson#41]
Hey,

I just had this crash while trying to navigate a nested JSON response. Sofar I can't reproduce the crash.

```
results := js.Get("response").Get("groups").GetIndex(0).Get("items").MustArray()
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5771ed]

goroutine 1436 [running]:
github.com/bitly/go-simplejson.(*Json).Map(0x0, 0xc208607ea0, 0x0, 0x0)
    /var/www/djscout-web/.go/src/github.com/bitly/go-simplejson/simplejson.go:176 +0x15d
github.com/bitly/go-simplejson.(*Json).Get(0x0, 0x8fd130, 0x8, 0x0)
    /var/www/djscout-web/.go/src/github.com/bitly/go-simplejson/simplejson.go:120 +0x28
_/var/www/djscout-web/djscout.GetLocationInformations(0xc208352460, 0xc208534580, 0xc208538460)
    /var/www/djscout-web/djscout/location.go:76 +0x9a7
created by main.Barcode
    /var/www/djscout-web/djscout-web.go:137 +0x163d
```

**Comment by xoen** [comment]
Hi @docterd , what's in the json? 

```go
b, _ := js.PrettyEncode()
fmt.Printf("json = '%s', b)
```

Is it possible that `response/group` is not there? Maybe that's the case and when `.GetIndex(0)` try to read the 1st element of an empty array blows up? Just a theory.
